// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxtqexzcsqaquutxyizm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14dHFleHpjc3FhcXV1dHh5aXptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwMDE4NTgsImV4cCI6MjA3MjU3Nzg1OH0.cQa1-tdCI8vdM7_L-yMp_zlUwWa7iiU7vGHwYMUoEkE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});